minimum_pre_commit_version: 4.6.0
exclude: '(^|/)(_archive|scripts|theme)(/|$)'
default_language_version:
  node: 26.5.0

repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: 5b5dddc4fb0f83c3ea1fc5616fa63e115dce83e0 # frozen: v0.49.1
    hooks:
      - id: markdownlint
        files: '^(src/.*\.md|README\.md|CONTRIBUTING\.md)'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: '^src/_[^/]+/'
      - id: trailing-whitespace
        entry: trailing-whitespace-fixer
        exclude: '^src/_[^/]+/'

  - repo: https://github.com/lycheeverse/lychee
    rev: 2bba271688c1abb1503097a064e6c3bc1d1b6a9b # frozen: lychee-v0.24.2
    hooks:
      - id: lychee
        alias: lychee-local
        name: check local links
        args: [ "--offline", "--no-progress" ]
        files: '^(src/.*\.md|README\.md|CONTRIBUTING\.md)'
        exclude: '^src/SUMMARY\.md$' # mdBook permits empty draft links.
      - id: lychee
        alias: lychee-external
        name: check external links
        args: [ "--no-progress", "--max-retries", "3" ]
        files: '^(src/.*\.md|README\.md|CONTRIBUTING\.md)'
        exclude: '^src/SUMMARY\.md$' # mdBook permits empty draft links.
        stages: [ manual ]
