[global]
# Lift MD041 exclusion if when allow_preamble is available
disable = ["MD028", "MD041"]
exclude = ["src/SUMMARY.md"]

[per-file-ignores]
# Remove when jsonspec.md link is fixed
"src/_include/auto/opcodes/byte-array-manipulation.md" = ["MD057"]
"src/avm/avm-appendix-a.md" = ["MD057"]

[MD013]
code-blocks = false
line-length = 120
tables = false

[MD033]
allowed-elements = ["a", "img"]
