name: CD

on:
  push:
    branches:
      - develop  # TODO: change to master

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
    with:
      artifact-name: mdbook-site-master

  deploy-pages:
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: mdbook-site-master
          path: book/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: book

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
