name: CI

on:
  pull_request:
    branches:
      - develop
  push:
    paths:
      - 'dev/**.md'
      - 'src/**'

permissions:
  contents: read
  deployments: write

jobs:
  integration:
    runs-on: ubuntu-latest
    name: Run acceptance
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker compose build

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          limit-access-to-actor: true
          limit-access-to-users: PhearZero
      - name: Run mdBook build
        run: docker compose run mdbook build

      - name: Upload the Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mdbook-build
          path: book

  deployment:
    needs:
      - integration
    runs-on: ubuntu-latest
    name: Run Cloudflare Deployment
    steps:
      - name: Download the Artifact
        uses: actions/download-artifact@v4
        with:
          name: mdbook-build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: |
            pages deploy . --project-name algorand-specs
