name: Release (Draft Updater)

on:
  release:
    types: [ created, edited ]

jobs:
  update-draft:
    if: ${{ github.event.release.prerelease == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get latest master commit short SHA
        id: sha
        run: echo "sha=$(git rev-parse --short origin/develop)" >> $GITHUB_OUTPUT  # TODO: change to master

      - name: Update draft release to short SHA tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const releaseId = context.payload.release.id;
            const sha = "${{ steps.sha.outputs.sha }}";

            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: releaseId,
              tag_name: sha,
              draft: true
            });

            core.info("Draft release tag updated to short SHA: " + sha);

      - name: Build Docker image
        run: docker compose build

      - name: Run mdBook build
        run: docker compose run mdbook build

      - name: Package HTML artifacts
        run: |
          mkdir -p release-artifacts
          tar -czf release-artifacts/specs-html.tar.gz -C book .

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-artifacts/specs-html.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}